all:
	mipsel-linux-gcc main.c sha1.c -o cfw_upgrade -lSDL_image -lSDL -lSDL_ttf -I/home/steward/Github/gh_retrogame_toolchain/mipsel-linux-gcc/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/include/SDL
	#gcc main.c sha1.c -g -o cfw_upgrade -lSDL_image -lSDL -lSDL_ttf -I/usr/include/SDL
clean:
	rm -rf upgrade
