# Automatically generated by configure
# Configured with: './configure' '--platform=opendingux' '--sound-drivers=sdl'
CC = mipsel-linux-gcc
CXX = mipsel-linux-g++
AS = mipsel-linux-as
STRIP = mipsel-linux-strip
CFLAGS +=  -I/home/steward/Downloads/buildroot-2017.02.9/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -Wno-unused-result
ASFLAGS += 
LDFLAGS += 
LDLIBS += -L/home/steward/Downloads/buildroot-2017.02.9/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/lib -lSDL -lpthread -lpng  -lm -lz

ARCH = mipsel
PLATFORM = opendingux
SOUND_DRIVERS = sdl
