all:
	mipsel-linux-gcc main.c -o overclock -lSDL_image -lSDL -lSDL_ttf -I/home/steward/Github/gh_retrogame_toolchain/mipsel-linux-gcc/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/include/SDL
	#gcc main.c -g -o overclock -DDEBUG -lSDL_image -lSDL -lSDL_ttf -I/usr/include/SDL
clean:
	rm -rf overclock
