CONFIG={};
CONFIG.Debug=0;
CONFIG.Type=1;
CONFIG.Rotate=0;
CONFIG.Width=420;
CONFIG.Height=480;
CONFIG.bpp=16;
CONFIG.FullScreen=0;
CONFIG.EnableSound=1;
CONFIG.KeyRepeat=0;
CONFIG.KeyRepeatDelay=30;
CONFIG.KeyRePeatInterval=30;
CONFIG.XScale=18;
CONFIG.YScale=9;
CONFIG.CurrentPath ="./";
CONFIG.DataPath=CONFIG.CurrentPath .. "data/";
CONFIG.PicturePath=CONFIG.CurrentPath .. "pic/";
CONFIG.SoundPath=CONFIG.CurrentPath .. "sound/";
CONFIG.ScriptPath=CONFIG.CurrentPath .. "script/";
CONFIG.OldEventPath=CONFIG.ScriptPath .. "oldevent/";
CONFIG.NewEventPath=CONFIG.ScriptPath .. "newevent/";
CONFIG.JYMain_Lua=CONFIG.ScriptPath .. "jymain.lua";
CONFIG.FontName="font/font.ttf";
CONFIG.OSCharSet=1
CONFIG.MMapAddX=2;
CONFIG.MMapAddY=2;
CONFIG.SMapAddX=2;
CONFIG.SMapAddY=16;
CONFIG.WMapAddX=2;
CONFIG.WMapAddY=18;
CONFIG.MusicVolume=24;
CONFIG.SoundVolume=32;
local LargeMemory=1;
if LargeMemory==1 then
  CONFIG.MAXCacheNum=1000;
	CONFIG.CleanMemory=0;
	CONFIG.LoadFullS=1;
	CONFIG.LoadMMapType=0;
	CONFIG.PreLoadPicGrp=1;
else
  CONFIG.MAXCacheNum=500;
	CONFIG.CleanMemory=1;
	CONFIG.LoadFullS=0;
	CONFIG.LoadMMapType=1;
	CONFIG.PreLoadPicGrp=0;
end
CONFIG.LoadMMapScope=0;          --部分加载主地图文件时的加载范围。坐标变化超过此值时就重新加载。此值*4即为实际加载的数据大小。
CONFIG.FastShowScreen=1;

